name: Build Test & Publish nuget package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/Swashbuckle.AspNetCore.ExtensionProperties
    steps:
    - name: Get Version
      run: |
        BASEVERSION=$(git describe --abbrev=0 --tags)
        echo "FULLVERSION=$BASEVERSION.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c release -p:Version=env.FULLVERSION
    - name: Test
      run: dotnet test --no-build --verbosity normal -c release
    - name: Package
      run: dotnet pack -c release
