name: Build Test & Publish nuget package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/Swashbuckle.AspNetCore.ExtensionProperties
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Get Version
      run: echo "FULLVERSION=$(git describe --abbrev=0 --tags).$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c release -p:Version=${{ env.FULLVERSION }}
    - name: Test
      run: dotnet test --no-build --verbosity normal -c release
    - name: Publish to Nuget
      run: dotnet nuget push bin/Release/Swashbuckle.AspNetCore.ExtensionProperties.${{ env.FULLVERSION }}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
